#!/usr/bin/env python3
"""Generate/check diagnostic signatures against the pinned native Engine.dll.
Also verify relocated operands, complete stolen instructions, and native RET ABI.
Usage: TQ_GAME_DIR=... python3 research/streaming/tools/verify-resource-trace.py [--write]
"""
import hashlib
import os
from pathlib import Path
import re
import struct
import subprocess
import sys
from pe import PE

ROOT = Path(__file__).resolve().parents[3]
ENGINE_HASH = '0aedbb1805b4a5616f74e34d4f609f392e2c2dd4561c64c118f4772ab4f694f6'
path = Path(os.environ['TQ_GAME_DIR']) / 'Engine.dll'
pe = PE(path)
assert hashlib.sha256(pe.data).hexdigest() == ENGINE_HASH, 'unreviewed Engine.dll'
# name, entry, stolen length, end (exclusive), callee stack cleanup
sites = [
    ('actor', 0x114f00, 7, 0x114f31, 8),
    ('mesh', 0x174e50, 6, 0x1750ce, 8),
    ('meshDependencies', 0x16eb50, 6, 0x16ec20, 0),
    ('shaderDependencies', 0x18b100, 6, 0x18b1a2, 0),
    ('actualLoad', 0x213a40, 8, 0x213bcb, 8),
    ('unload', 0x212c70, 7, 0x212cc6, 4),
    ('construct', 0x212e60, 7, 0x212f4a, 12),
]
reloc_rva, reloc_size = struct.unpack_from('<II', pe.data, pe.opt + 96 + 5 * 8)
relocs = []
offset = 0
while offset < reloc_size:
    page, size = struct.unpack('<II', pe.read(reloc_rva + offset, 8))
    assert size >= 8
    for item in struct.unpack('<' + 'H' * ((size - 8) // 2), pe.read(reloc_rva + offset + 8, size - 8)):
        if item >> 12 == 3:
            relocs.append(page + (item & 0xfff))
        else:
            assert item >> 12 == 0
    offset += size

def signature(name, start, size):
    # Never cut through an ASLR operand, even at the end of a verification window.
    while any(start <= r < start + size < r + 4 for r in relocs):
        size += 1
    assert size <= 48
    data = bytearray(pe.read(start, size))
    relocations = []
    for r in relocs:
        if start <= r < start + size:
            i = r - start
            target = struct.unpack_from('<I', data, i)[0] - pe.base
            assert 0 <= target < pe.imagesize
            relocations.append((i, target))
            data[i:i+4] = b'\0' * 4
    output = f'const BYTE {name}[] = {{' + ', '.join(f'0x{b:02x}' for b in data) + '};\n'
    if relocations:
        output += f'const tq::detour::Relocation {name}_rel[] = {{' + ', '.join(f'{{{i}, {r:#x}}}' for i, r in relocations) + '};\n'
    expression = f'{{{name}, sizeof({name}), ' + (f'{name}_rel, {len(relocations)}' if relocations else 'nullptr, 0') + '}'
    return output, expression

output = f'// Native Engine.dll SHA-256: {ENGINE_HASH}\n'
output += '// Generated by research/streaming/tools/verify-resource-trace.py --write.\n'
output += '// See research/streaming/mesh-preload-lifecycle.md for ABI and caller verification.\n'
output += 'namespace {\nstruct Site { DWORD rva; unsigned stolen; tq::detour::Signature signature;\n    DWORD tailRva; tq::detour::Signature tail; const void* hook; void** original; };\n'
rows = []
for name, start, stolen, end, cleanup in sites:
    ret = b'\xc2' + struct.pack('<H', cleanup) if cleanup else b'\xc3'
    assert pe.read(end - len(ret), len(ret)) == ret, f'{name}: native return ABI'
    asm = subprocess.check_output(['i686-w64-mingw32-objdump', '-d', '-Mintel',
        f'--start-address={pe.base + start}', f'--stop-address={pe.base + start + 48}', str(path)], text=True)
    consumed = 0
    for line in asm.splitlines():
        m = re.match(r'\s*([0-9a-f]+):\s*((?:[0-9a-f]{2} )+)\s*(.*)', line)
        if not m or int(m[1], 16) != pe.base + start + consumed:
            continue
        instruction = m[3].strip()
        assert instruction and not re.match(r'(j\w*|call|loop\w*)\b', instruction), f'{name}: relocated control flow'
        consumed += len(m[2].split())
        if consumed >= stolen:
            break
    assert consumed == stolen, f'{name}: split stolen instruction'
    head_text, head_expr = signature(name + '_head', start, 32)
    tail_text, tail_expr = signature(name + '_tail', end - 8, 8)
    output += head_text + tail_text
    rows.append(f'    {{{start:#x}, {stolen}, {head_expr}, {end - 8:#x}, {tail_expr}, (void*)&{name}, (void**)&g_{name}}},\n')
output += 'const Site kSites[] = {\n' + ''.join(rows) + '};\n} // namespace\n'
target = ROOT / 'src/resource_trace_sites.inc'
if '--write' in sys.argv:
    target.write_text(output)
else:
    assert target.read_text() == output, 'resource trace signatures differ from audited binary'
print('PASS: 7 resource lifecycle sites, ASLR operands, stolen instructions, native return ABI')
