#!/usr/bin/env bash
# Derive every vtable slot index Stage 4 patches from the MinGW headers.
#
#   scripts/gen-slots.sh OUTDIR
#
# Writes OUTDIR/slots.h: one `#define TQ_SLOT_<Iface>_<Method> N` per method we
# hook, with N read off the C `<Iface>Vtbl` struct in the header that the DLL is
# compiled against. **No slot number in this project is typed by hand.** A
# remembered index that is off by one is a hook that silently lands on the
# neighbouring method - which either never fires or crashes the game on a call
# with the wrong argument count (stdcall: the callee pops the stack), and neither
# symptom points at the real cause.
#
# The MinGW Vtbl structs are flattened (base-interface methods first), so the
# 0-based position of a member is its slot. Checked against the running game:
# O19 saw the swapchain/context/device vtables at stable addresses, and the
# `VT ... slot N` lines in the log say which index each build used.
set -euo pipefail
OUT="${1:?OUTDIR}"
mkdir -p "$OUT"

INC="$(dirname "$(i686-w64-mingw32-g++ -print-file-name=libstdc++.a)")"
# libstdc++.a sits under <prefix>/i686-w64-mingw32/lib/...; the headers are the
# sibling include directory. Walk up until one has d3d11.h.
D=""
for c in "$INC/.." "$INC/../.." "$INC/../../.." "$INC/../../../.." "$INC/../../../../.."; do
  if [ -f "$c/i686-w64-mingw32/include/d3d11.h" ]; then D="$c/i686-w64-mingw32/include"; break; fi
  if [ -f "$c/include/d3d11.h" ]; then D="$c/include"; break; fi
done
[ -n "$D" ] || { echo "gen-slots: cannot find d3d11.h under the i686 MinGW prefix" >&2; exit 1; }

# The method names of <Iface>Vtbl, in declaration order, one per line.
methods() {  # header iface
  awk "/^typedef struct ${2}Vtbl/,/^} ${2}Vtbl/" "$D/$1" | grep -oE '\*[A-Za-z0-9_]+\)\(' | tr -d '*)('
}

emit() {  # header iface method...
  local hdr="$1" iface="$2"; shift 2
  local list; list="$(methods "$hdr" "$iface")"
  local n; n="$(printf '%s\n' "$list" | wc -l | tr -d ' ')"
  echo "#define TQ_SLOTS_${iface} ${n}   /* methods in ${iface}Vtbl */"
  for m in "$@"; do
    local i; i="$(printf '%s\n' "$list" | grep -nx "$m" | head -1 | cut -d: -f1)"
    [ -n "$i" ] || { echo "gen-slots: $iface has no method $m in $hdr" >&2; exit 1; }
    echo "#define TQ_SLOT_${iface}_${m} $((i - 1))"
  done
}

{
  echo "// Generated by scripts/gen-slots.sh from $D - do not edit."
  echo "#pragma once"
  emit dxgi.h  IDXGISwapChain Present
  emit d3d11.h ID3D11DeviceContext DrawIndexed Draw DrawIndexedInstanced DrawInstanced \
       DrawAuto DrawIndexedInstancedIndirect DrawInstancedIndirect ExecuteCommandList \
       Map Unmap VSSetConstantBuffers PSSetConstantBuffers GSSetConstantBuffers \
       HSSetConstantBuffers DSSetConstantBuffers CSSetConstantBuffers IASetVertexBuffers IASetIndexBuffer OMSetRenderTargets
  emit d3d11.h ID3D11Device CreateBuffer CreateVertexShader CreatePixelShader CreateSamplerState
} > "$OUT/slots.h"
echo "gen-slots: $OUT/slots.h"
